name: Publish Edge Docker images

on:
  schedule:
    - cron: "0 23 * * *"
  push:
    branches:
      - main

jobs:
  push_jojo_bot_edge:
    name: "JoJo Discord Bot ${{ matrix.tag }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag:
          - "edge"
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
        with:
          version: "v0.5.1"
          buildkitd-flags: --debug
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN  }}
      - uses: docker/build-push-action@v2
        with:
          context: ./eggs/jojo-discord-bot/image
          file: ./eggs/jojo-discord-bot/image/${{ matrix.tag }}/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/lazybytez/custom-eggs:jojo-discord-bot_${{ matrix.tag }}
